name: Publish releases to PyPI

on:
    workflow_run:
        workflows: ["Check and create tag"]
        types:
            - completed
        branches:
            - master

jobs:
    package_build:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Build and publish to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/vswobbly
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

            - name: Build wheel and source distribution
              run: uv build --no-sources

            - name: Check the output
              run: uvx twine check --strict dist/*

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
